version: "3"

services:
    app:
        build: .
        ports: 
            - "8000:8000"
        volumes:
            - .:/code
        links:
            - postgres
        depends_on:
            - postgres
        stdin_open: true
        tty: true
    postgres:
        image: postgres:latest
        volumes:
            - pgdata:/var/lib/postgresql/data/
volumes:
    pgdata: