# Generated by Django 3.0.2 on 2020-01-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errata',
            name='openstax_book',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
