# Generated by Django 2.2.8 on 2020-03-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0002_errata_openstax_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errata',
            name='openstax_book',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
