# Generated by Django 3.0.2 on 2020-03-20 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0003_auto_20200309_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errata',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='errata.Book'),
        ),
    ]
