# Generated by Django 3.0.2 on 2020-04-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0004_auto_20200320_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errata',
            name='book',
        ),
        migrations.AlterField(
            model_name='errata',
            name='openstax_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='errata.Book'),
        ),
    ]
